THEME_DATABASE = {
    "Персонажи Marvel": [
        ["железный человек", "iron man", "тони старк", "tony stark"],
        ["человек паук", "человек-паук", "спайдермен", "spider man", "spider-man", "питер паркер", "peter parker"],
        ["дэдпул", "дедпул", "deadpool", "уэйд уилсон", "wade wilson"],
        ["тор", "thor"],
        ["халк", "hulk", "брюс беннер", "bruce banner"],
        ["капитан америка", "captain america", "стив роджерс", "steve rogers"],
        ["черная вдова", "black widow", "наташа романофф", "natasha romanoff"],
        ["локи", "loki"],
        ["танос", "thanos"],
        ["доктор стрэндж", "доктор стрендж", "doctor strange", "стрэндж", "стрендж"],
        ["росомаха", "wolverine", "логан", "logan"],
        ["соколиный глаз", "hawkeye", "клинт бартон", "clint barton"],
        ["черная пантера", "black panther", "тчалла", "tchalla"],
        ["человек муравей", "человек-муравей", "ant man", "ant-man", "скотт лэнг", "scott lang"],
        ["алая ведьма", "scarlet witch", "ванда максимофф", "wanda maximoff"],
        ["вижн", "vision"],
        ["ник фьюри", "nick fury", "фьюри", "fury"],
        ["капитан марвел", "captain marvel", "кэрол дэнверс", "carol danvers"],
        ["звездный лорд", "star lord", "star-lord", "питер квилл", "peter quill"],
        ["гамора", "gamora"],
        ["ракета", "rocket raccoon", "енот ракета"],
        ["грут", "groot"],
        ["дракс", "drax", "дракс разрушитель"],
        ["мантис", "mantis"],
        ["веном", "venom", "эдди брок", "eddie brock"],
        ["карнаж", "carnage"],
        ["зеленый гоблин", "green goblin", "норман озборн", "norman osborn"],
        ["доктор осьминог", "doctor octopus", "док ок", "doc ock", "отто октавиус", "otto octavius"],
        ["магнето", "magneto", "эрик леншерр", "erik lehnsherr"],
        ["профессор икс", "professor x", "чарльз ксавьер", "charles xavier"],
        ["циклоп", "cyclops"],
        ["шторм", "storm"],
        ["джина грей", "jean grey"],
        ["зверь", "beast"],
        ["ртуть", "quicksilver", "пьетро максимофф", "pietro maximoff"],
        ["сокол", "falcon", "сэм уилсон", "sam wilson"],
        ["зимний солдат", "winter soldier", "баки барнс", "bucky barnes", "баки", "bucky"],
        ["воитель", "war machine", "роуди", "rowdy"],
        ["сорвиголова", "daredevil", "мэтт мердок", "matt murdock"],
        ["каратель", "punisher", "фрэнк касл", "frank castle"],
        ["мистерио", "mysterio"],
        ["электро", "electro"]
    ],
    "Персонажи Гарри Поттера": [
        ["гарри поттер", "harry potter", "гарри", "harry"],
        ["гермиона грейнджер", "hermione granger", "гермиона", "hermione"],
        ["рон уизли", "ron weasley", "рон", "ron"],
        ["альбус дамблдор", "albus dumbledore", "дамблдор", "dumbledore"],
        ["северус снейп", "severus snape", "снейп", "snape", "северус снегг", "снегг", "северус"],
        ["волан де морт", "волан-де-морт", "волдеморт", "voldemort", "том реддл", "tom riddle", "самый-знаешь-кто", "тот-кого-нельзя-называть"],
        ["драко малфой", "draco malfoy", "драко", "draco", "малфой", "malfoy"],
        ["рубеус хагрид", "rubeus hagrid", "хагрид", "hagrid"],
        ["сириус блэк", "sirius black", "сириус", "sirius", "бродяга", "padfoot"],
        ["римус люпин", "remus lupin", "люпин", "lupin", "лунатик", "moony"],
        ["минерва макгонагалл", "minerva mcgonagall", "макгонагалл", "mcgonagall"],
        ["добби", "dobby"],
        ["полумна лавгуд", "полумна", "luna lovegood", "luna", "луна лавгуд"],
        ["невилл долгопупс", "невилл лонгботтом", "neville longbottom", "невилл", "neville"],
        ["джинни уизли", "ginny weasley", "джинни", "ginny"],
        ["фред уизли", "fred weasley", "фред", "fred"],
        ["джордж уизли", "george weasley", "джордж", "george"],
        ["беллатриса лестрейндж", "беллатрикс лестрейндж", "bellatrix lestrange", "беллатриса", "беллатрикс", "bellatrix"],
        ["люциус малфой", "lucius malfoy", "люциус", "lucius"],
        ["питер петтигрю", "peter pettigrew", "хвост", "wormtail"],
        ["лили поттер", "lily potter", "лили", "lily"],
        ["джеймс поттер", "james potter", "джеймс", "james", "сохатый", "prongs"],
        ["седрик диггори", "cedric diggory", "седрик", "cedric"],
        ["аргус филч", "филч", "filch"],
        ["дадли дурсль", "дадли", "dudley dursley", "dudley"],
        ["вернон дурсль", "вернон", "vernon dursley", "vernon"],
        ["петунья дурсль", "петунья", "petunia dursley", "petunia"],
        ["фоукс", "fawkes"],
        ["букля", "hedwig", "хедвиг"],
        ["плакса миртл", "миртл", "moaning myrtle", "myrtle"],
        ["златопуст локонс", "гилдерой локхарт", "gilderoy lockhart", "локонс", "локхарт"],
        ["аластор грюм", "грозный глаз", "грюм", "alastor moody", "mad-eye moody", "moody"]
    ],
    "Страны Европы": [
        ["россия", "russia", "рф", "russian federation", "российская федерация"],
        ["германия", "germany", "deutschland"],
        ["франция", "france"],
        ["италия", "italy", "italia"],
        ["испания", "spain", "espana"],
        ["великобритания", "англия", "united kingdom", "england", "uk", "британия", "great britain"],
        ["польша", "poland", "polska"],
        ["украина", "ukraine"],
        ["румыния", "romania"],
        ["нидерланды", "голландия", "netherlands", "holland"],
        ["бельгия", "belgium"],
        ["греция", "greece"],
        ["португалия", "portugal"],
        ["швеция", "sweden"],
        ["австрия", "austria"],
        ["швейцария", "switzerland"],
        ["болгария", "bulgaria"],
        ["венгрия", "hungary"],
        ["беларусь", "белоруссия", "belarus"],
        ["чехия", "czechia", "czech republic"],
        ["сербия", "serbia"],
        ["словакия", "slovakia"],
        ["дания", "denmark"],
        ["финляндия", "finland"],
        ["норвегия", "norway"],
        ["ирландия", "ireland"],
        ["хорватия", "croatia"],
        ["молдова", "молдавия", "moldova"],
        ["босния", "босния и герцеговина", "bosnia"],
        ["албания", "albania"],
        ["литва", "lithuania"],
        ["северная македония", "македония", "macedonia"],
        ["словения", "slovenia"],
        ["латвия", "latvia"],
        ["эстония", "estonia"],
        ["черногория", "montenegro"],
        ["люксембург", "luxembourg"],
        ["мальта", "malta"],
        ["исландия", "iceland"],
        ["андорра", "andorra"],
        ["монако", "monaco"],
        ["лихтенштейн", "liechtenstein"],
        ["сан марино", "сан-марино", "san marino"],
        ["ватикан", "vatican"]
    ],
    "Языки программирования": [
        ["python", "питон", "пайтон"],
        ["javascript", "джаваскрипт", "яваскрипт", "js", "жс"],
        ["java", "джава", "ява"],
        ["c++", "си плюс плюс", "cpp", "цпп"],
        ["c", "си"],
        ["c#", "си шарп", "c sharp"],
        ["php", "пхп", "пых", "пэхапэ"],
        ["ruby", "руби"],
        ["go", "го", "golang"],
        ["rust", "раст"],
        ["swift", "свифт"],
        ["kotlin", "котлин"],
        ["typescript", "тайпскрипт", "ts", "тс"],
        ["html", "хтмл"],
        ["css", "цсс"],
        ["sql", "скьюэль", "сиквел"],
        ["perl", "перл"],
        ["scala", "скала"],
        ["r", "эр"],
        ["bash", "баш", "shell", "шелл"],
        ["dart", "дарт"],
        ["assembly", "ассемблер", "asm"],
        ["pascal", "паскаль"],
        ["delphi", "дельфи"],
        ["lisp", "лисп"],
        ["haskell", "хаскелл"],
        ["lua", "луа"],
        ["cobol", "кобол"],
        ["fortran", "фортран"],
        ["basic", "бейсик"],
        ["scratch", "скрэтч", "скретч"]
    ],
    "Марки автомобилей": [
        ["toyota", "тойота"],
        ["ford", "форд"],
        ["chevrolet", "шевроле", "шевроле"],
        ["honda", "хонда"],
        ["hyundai", "хендай", "хёндай", "хундай"],
        ["kia", "киа"],
        ["nissan", "ниссан"],
        ["volkswagen", "фольксваген", "vw", "фольц", "фолькс"],
        ["bmw", "бмв", "беха", "бэха"],
        ["mercedes", "мерседес", "mercedes-benz", "бенз", "мерс"],
        ["audi", "ауди", "аудос", "аудиха"],
        ["lexus", "лексус", "лекс"],
        ["mazda", "мазда", "маздочка"],
        ["subaru", "субару", "субарь", "субарик"],
        ["porsche", "порше", "порш"],
        ["ferrari", "феррари"],
        ["lamborghini", "ламборгини", "ламборджини", "ламба"],
        ["tesla", "тесла"],
        ["volvo", "вольво"],
        ["peugeot", "пежо"],
        ["renault", "рено"],
        ["fiat", "фиат"],
        ["opel", "опель"],
        ["skoda", "шкода"],
        ["lada", "лада", "ваз", "жигули"],
        ["jeep", "джип"],
        ["land rover", "ленд ровер", "лэнд ровер"],
        ["mitsubishi", "митсубиси", "митсубиши", "митсу"],
        ["rolls royce", "роллс ройс", "роллс-ройс"],
        ["bentley", "бентли"],
        ["bugatti", "бугатти"],
        ["jaguar", "ягуар"],
        ["aston martin", "астон мартин"],
        ["cadillac", "кадиллак"],
        ["dodge", "додж"],
        ["chrysler", "крайслер"]
    ],
    "Блюда итальянской кухни": [
        ["pizza", "пицца"],
        ["pasta", "паста", "макароны", "спагетти", "spaghetti"],
        ["lasagna", "лазанья"],
        ["tiramisu", "тирамису"],
        ["risotto", "ризотто"],
        ["ravioli", "равиоли"],
        ["bruschetta", "брускетта"],
        ["gnocchi", "ньокки"],
        ["minestrone", "минестроне"],
        ["caprese", "капрезе"],
        ["carpaccio", "карпаччо"],
        ["polenta", "полента"],
        ["focaccia", "фокачча"],
        ["panna cotta", "панна котта", "панна-котта"],
        ["calzone", "кальцоне"],
        ["carbonara", "карбонара"],
        ["bolognese", "болоньезе"],
        ["pesto", "песто"],
        ["frittata", "фриттата"],
        ["gelato", "джелато", "мороженое"],
        ["arancini", "аранчини"],
        ["ciabatta", "чиабатта"]
    ],
    "Социальные сети и мессенджеры": [
        ["telegram", "телеграм", "телега", "tg", "тг"],
        ["whatsapp", "ватсап", "вотсап", "вацап", "wa"],
        ["viber", "вайбер"],
        ["vk", "вконтакте", "вк", "vkontakte"],
        ["instagram", "инстаграм", "инста", "инстаграмм"],
        ["facebook", "фейсбук", "фб", "fb"],
        ["youtube", "ютуб", "ютуп", "yt"],
        ["tiktok", "тикток", "тик ток"],
        ["twitter", "твиттер", "x", "икс"],
        ["reddit", "реддит"],
        ["discord", "дискорд", "дс", "ds"],
        ["snapchat", "снапчат", "снап"],
        ["linkedin", "линкедин"],
        ["pinterest", "пинтерест", "пин"],
        ["skype", "скайп"],
        ["zoom", "зум"],
        ["twitch", "твитч", "твич"],
        ["slack", "слэк", "слек"],
        ["line", "лайн"],
        ["wechat", "вичат"]
    ],
    "Фрукты и ягоды": [
        ["яблоко", "apple"],
        ["груша", "pear"],
        ["банан", "banana"],
        ["апельсин", "orange"],
        ["мандарин", "mandarin", "tangerine"],
        ["лимон", "lemon"],
        ["лайм", "lime"],
        ["грейпфрут", "grapefruit"],
        ["ананас", "pineapple"],
        ["киви", "kiwi"],
        ["манго", "mango"],
        ["персик", "peach"],
        ["абрикос", "apricot"],
        ["слива", "plum"],
        ["вишня", "черешня", "cherry"],
        ["клубника", "земляника", "strawberry"],
        ["малина", "raspberry"],
        ["черника", "голубика", "blueberry"],
        ["ежевика", "blackberry"],
        ["арбуз", "watermelon"],
        ["дыня", "melon"],
        ["гранат", "pomegranate"],
        ["виноград", "grape"],
        ["кокос", "coconut"],
        ["авокадо", "avocado"],
        ["инжир", "fig"],
        ["папайя", "papaya"],
        ["маракуйя", "passion fruit"]
    ],
    "Олимпийские виды спорта": [
        ["футбол", "football", "soccer"],
        ["баскетбол", "basketball"],
        ["волейбол", "volleyball"],
        ["теннис", "tennis"],
        ["плавание", "swimming"],
        ["легкая атлетика", "бег", "athletics", "running"],
        ["гимнастика", "gymnastics"],
        ["бокс", "boxing"],
        ["дзюдо", "judo"],
        ["карате", "каратэ", "karate"],
        ["борьба", "wrestling"],
        ["тяжелая атлетика", "weightlifting"],
        ["велоспорт", "cycling"],
        ["гребля", "rowing"],
        ["парусный спорт", "sailing"],
        ["стрельба", "shooting"],
        ["стрельба из лука", "archery"],
        ["фехтование", "fencing"],
        ["гандбол", "handball"],
        ["бадминтон", "badminton"],
        ["настольный теннис", "пинг-понг", "table tennis", "ping pong"],
        ["конный спорт", "equestrian"],
        ["триатлон", "triathlon"],
        ["хоккей", "ice hockey", "hockey"],
        ["фигурное катание", "figure skating"],
        ["сноуборд", "snowboarding"],
        ["лыжный спорт", "лыжи", "skiing"],
        ["биатлон", "biathlon"],
        ["керлинг", "кёрлинг", "curling"],
        ["бобслей", "bobsleigh"]
    ],
    "Животные Африки": [
        ["лев", "lion"],
        ["зебра", "zebra"],
        ["жираф", "giraffe"],
        ["слон", "elephant"],
        ["бегемот", "гиппопотам", "hippo", "hippopotamus"],
        ["носорог", "rhino", "rhinoceros"],
        ["гепард", "cheetah"],
        ["леопард", "leopard"],
        ["гиена", "hyena"],
        ["горилла", "gorilla"],
        ["шимпанзе", "chimpanzee", "chimp"],
        ["обезьяна", "monkey"],
        ["сурикат", "meerkat"],
        ["лемур", "lemur"],
        ["крокодил", "crocodile"],
        ["буйвол", "buffalo"],
        ["страус", "ostrich"],
        ["фламинго", "flamingo"],
        ["антилопа", "antelope"],
        ["верблюд", "camel"],
        ["фенек", "fennec fox", "fennec"],
        ["бородавочник", "warthog"],
        ["питон", "python"]
    ]
}
